### ISSUE TITLE
Crash on location.reload()

### ISSUE THREAD

**Issue by alexplummer** [Instabug/instabug-cordova#23]
My app is continuously crashing every time location.reload() is called, check out the log:

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2720)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
  at android.app.ActivityThread.-wrap12(ActivityThread.java:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:241)
  at android.app.ActivityThread.main(ActivityThread.java:6274)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: 
  at com.instabug.library.messaging.b.a.e(SynchronizationManager.java:100)
  at com.instabug.library.messaging.b.a.d(SynchronizationManager.java:120)
  at com.instabug.library.f.x(InstabugDelegate.java:335)
  at com.instabug.library.f.g(InstabugDelegate.java:303)
  at com.instabug.library.Instabug.disable(Instabug.java:761)
  at com.instabug.library.Instabug$Builder.build(Instabug.java:2343)
  at com.instabug.cordova.plugin.IBGPluginActivity.onCreate(IBGPluginActivity.java:53)
  at android.app.Activity.performCreate(Activity.java:6720)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2673)

**Comment by salmatarzi** [comment]
@alexplummer I know this issue has been there for a while, I'm really sorry for that. This looks like it is a problem from the Native Android SDK, I will forward it to our Android team to look into it.

**Comment by randaelbaz** [comment]
Hi @alexplummer 
This issue has been there for a while, here is an update, please update to the latest version (1.2.3). I will close this issue, for now, please reopen if the problem still persists.
