### ISSUE TITLE
Failed to install due to multidex dependancie

### ISSUE THREAD

**Issue by Slavrix** [Instabug/instabug-cordova#25]
When trying to install I get this error.

installing with
 
`cordova plugin add https://github.com/Instabug/instabug-cordova --save`
```
Failed to install 'com.instabug.cordova.plugin': Error
    at C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:205:33
    at _rejected (C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
    at C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
    at C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:624:44
    at runSingle (C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
    at flush (C:\Users\rusty\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Error: Failed to fetch plugin https://github.com/chris-armstrong/cordova-multidex via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by Slavrix** [comment]
If your using cordova 7.*+

youll need to add the -nofetch flag to install this without it failing
