### ISSUE TITLE
Instabug getInstance called before Instabug.Builder().build() was called

### ISSUE THREAD

**Issue by Malrok** [Instabug/instabug-cordova#38]
Hello,

I have an Android application with the Instabug plugin installed.
When launching it, it crashes immaediatly with the following error found in logcat:

    FATAL EXCEPTION: main
    Process: org.sahfa.jambomama.women, PID: 25648
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sahfa.jambomama.women/com.instabug.cordova.plugin.IBGPluginActivity}: java.lang.IllegalStateException: Instabug getInstance called before Instabug.Builder().build() was called
           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2805)
           at android.app.ActivityThread.-wrap12(ActivityThread.java)
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1518)
           at android.os.Handler.dispatchMessage(Handler.java:102)
           at android.os.Looper.loop(Looper.java:173)
           at android.app.ActivityThread.main(ActivityThread.java:6519)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:849) 09-27 17:34:33.615 25648 25648 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Instabug getInstance called before Instabug.Builder().build() was called
           at com.instabug.library.Instabug.getInstance(Instabug.java:82)
           at com.instabug.library.Instabug.setCommentFieldRequired(Instabug.java:1422)
           at com.instabug.cordova.plugin.IBGPluginActivity.setCommentFieldRequired(IBGPluginActivity.java:63)
           at com.instabug.cordova.plugin.IBGPluginActivity.setBuilderOptions(IBGPluginActivity.java:249)
           at com.instabug.cordova.plugin.IBGPluginActivity.onCreate(IBGPluginActivity.java:34)
           at android.app.Activity.performCreate(Activity.java:6688)
           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2697)
           ... 9 more
     App crashed! Process: org.sahfa.jambomama.women
       Force finishing activity org.sahfa.jambomama.women/com.instabug.cordova.plugin.IBGPluginActivity

**Comment by reemalashry1** [comment]
Hello @Malrok 
Would you please tell me the SDK version you are on?

**Comment by Malrok** [comment]
Hello,
We are using version 1.3.4 of instabug-cordova.
I have attached the manifest file and the app.js with the instabug initialization code.

Thanks

[instabug.zip](https://github.com/Instabug/instabug-cordova/files/1348246/instabug.zip)

**Comment by reemalashry1** [comment]
Hey @Malrok 
Would you please add this line under the application tag in your manifest file: `android:name=“com.instabug.cordova.plugin.MyApplication”` 
Please let me know how it goes 😊

**Comment by Malrok** [comment]
Hi,
It is launching now, but I cannot see the Instabug widget...

**Comment by reemalashry1** [comment]
@Malrok Do you mean the button?
If yes, you can change the invocation event to be the floating button by using  `InstabugInvocationEvent.FLOATING_BUTTON` in the `MyApplication` class.

**Comment by ZiadAyman** [comment]
Hey @Malrok I am following up with you to check that everything is in place. Can you now see the floating button? Any problems still occuring?

**Comment by malrok44** [comment]
Hello,
The button is visible, and everything is working fine.
Thanks for your help 😊

**Comment by ZiadAyman** [comment]
@Malrok Perfect! Glad to know everything is going good at your side. I will close this issue for now but please don't hesitate to get back to us whenever you need any help :)
