### ISSUE TITLE
Adobe Phonegap Build Error

### ISSUE THREAD

**Issue by asangadev** [Instabug/instabug-cordova#40]
Hi,

I’m having some issues with Adobe Phonegap Build.

I have below plugins in my config.xml file:

```
<plugin name="cordova-plugin-dialogs" spec="~1.2.1" />
<plugin name="cordova-plugin-file" spec="~4.1.1" />
<plugin name="cordova-plugin-globalization" spec="~1.0.8" />
<plugin name="cordova-plugin-inappbrowser" spec="~1.3.0" />
<plugin name="cordova-plugin-network-information" spec="~1.2.1" />
<plugin name="cordova-plugin-splashscreen" spec="~3.2.2" />
<plugin name="cordova-plugin-statusbar" spec="~2.3.0" />
<plugin name="cordova-launch-review" spec="~2.0.2" />
<plugin name="cordova-plugin-badge" spec="~0.8.5" />
<plugin name="cordova-plugin-geolocation" spec="~3.0.0" />
<plugin name="cordova-open-native-settings" spec="~1.4.1" />
<plugin name="com.localytics.phonegap.LocalyticsPlugin" spec="~1.0.0" />
<plugin name="cordova.plugins.diagnostic" spec="~3.7.2" />
```

I can create the APK file without having any issues with above plugin list. If I add below to the config.xml I’m getting an error in Adobe Phongegap Build.

LINE:
`<plugin name="com.instabug.cordova.plugin" spec="https://github.com/Instabug/instabug-cordova" />`

ERROR:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Could you please help me with this?

**Comment by asangadev** [comment]
issue was the "cordova-plugin-file" plugin. I have to update it to the latest version.

`<plugin name="cordova-plugin-file" spec="~5.0.0" />`
