### ISSUE TITLE
Android App Crashing Issue

### ISSUE THREAD

**Issue by sreeraj137** [Instabug/instabug-cordova#52]
App crashing after changing  network connection.

java.lang.RuntimeException: Unable to instantiate receiver com.instabug.library.network.InstabugNetworkReceiver: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.amritatech.amritaswift-1/base.apk"],nativeLibraryDirectories=[/data/app/com.amritatech.amritaswift-1/lib/x86, /vendor/lib, /system/lib]]
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2706)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.amritatech.amritaswift-1/base.apk"],nativeLibraryDirectories=[/data/app/com.amritatech.amritaswift-1/lib/x86, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2701)

**Comment by Korazy** [comment]
Hey @sreeraj137, thanks for pointing that out. We'll look into getting a fix out for it as soon as possible.

**Comment by Korazy** [comment]
@sreeraj137 can you please let me know if you have MultiDex enabled? If not, can you please enable it?

**Comment by sreeraj137** [comment]
We have enabled MultiDex. Issue still exists.

**Comment by aswathys26** [comment]
The same issue was happened with my app also. I have checked our application apk and found a class b.smali where source name is given as InstabugNetworkReceiver.java but class name was given as b. So in android.json file I have changed the classname from InstabugNetworkReceiver to b, and the issue of crashing the app during connectivity change has gone . Is this is a right way to resolve this issue?

**Comment by Korazy** [comment]
@sreeraj137 we're looking into the issue now.
@aswathys26 thank you for the information, we'll look into it as well!

**Comment by Korazy** [comment]
@sreeraj137 can you please tell me which Instabug Cordova version you're using?

**Comment by sreeraj137** [comment]
We are using instabug of version "1.10.0"

**Comment by salmatarzi** [comment]
@sreeraj137 @aswathys26 This issue has been fixed in "1.11.1"
