### ISSUE TITLE
Android app fails runtime

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instabug/instabug-cordova#55]
Hi guys,

Simply starting the application on Android emulator results in an immediate crash, as shown in the following log:

```
   Process: app.myapplication, PID: 17029
    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.norbert/com.instabug.cordova.plugin.IBGPluginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.settings.b.a(com.instabug.library.InstabugColorTheme)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.settings.b.a(com.instabug.library.InstabugColorTheme)' on a null object reference
        at com.instabug.library.settings.SettingsManager.setTheme(SettingsManager.java:250)
        at com.instabug.library.Instabug.setTheme(Instabug.java:1804)
        at com.instabug.cordova.plugin.IBGPluginActivity.setColorTheme(IBGPluginActivity.java:272)
        at com.instabug.cordova.plugin.IBGPluginActivity.setBuilderOptions(IBGPluginActivity.java:300)
        at com.instabug.cordova.plugin.IBGPluginActivity.onCreate(IBGPluginActivity.java:35)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
``` 

I'm using `ionic` with `cordova`, here's the `ionic info` output: 

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.7.1 
``` 

Within my `package.json` file: 

- `instabug-cordova`: `^1.14.1`

**Comment by ramiimagdi** [comment]
Hey @MattiaPrimavera 

Thanks for reaching out to us with this. We'll check it out and get back to you.

**Comment by ramiimagdi** [comment]
@MattiaPrimavera 
Can you please share with us your Instabug code? And if possible, the steps you followed that led to the crash?

**Comment by ramiimagdi** [comment]
Hey @MattiaPrimavera, hope you're doing well.
I was wondering if you had a chance to catch my previous message. Please let me know if I can help you with anything.

**Comment by ramiimagdi** [comment]
@MattiaPrimavera Thank you for reaching out to us, please don't hesitate to reach out to us if you have any questions.
