### ISSUE TITLE
Fresh install of plugin crashes

### ISSUE THREAD

**Issue by luckylooke** [Instabug/instabug-cordova#65]
I have created new ionic project and build to device, everything was fine, then I have installed instabug cordova plugin and tried again, but build fails:
```
cordova run android
[cordova]  Android Studio project detected
[cordova]  ANDROID_HOME=/Users/myUser/Library/Android/sdk
[cordova]  JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
[cordova]  studio
[cordova]  Subproject Path: CordovaLib
[cordova]  Subproject Path: app
[cordova]  publishNonDefault is deprecated and has no effect anymore. All variants are now published.
[cordova]  The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
[cordova]  	at build_5uwp26o1t35f611bk62346ybi.run(/Users/myUser/Documents/projects/myProject/platforms/android/app/build.gradle:149)
[cordova]  Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
[cordova]  :CordovaLib:preBuild UP-TO-DATE
[cordova]  :CordovaLib:preDebugBuild UP-TO-DATE
[cordova]  :CordovaLib:compileDebugAidl UP-TO-DATE
[cordova]  :CordovaLib:compileDebugRenderscript UP-TO-DATE
[cordova]  :CordovaLib:checkDebugManifest UP-TO-DATE
[cordova]  :CordovaLib:generateDebugBuildConfig UP-TO-DATE
[cordova]  :CordovaLib:prepareLintJar UP-TO-DATE
[cordova]  :CordovaLib:generateDebugResValues UP-TO-DATE
[cordova]  :CordovaLib:generateDebugResources UP-TO-DATE
[cordova]  :CordovaLib:packageDebugResources UP-TO-DATE
[cordova]  :CordovaLib:platformAttrExtractor UP-TO-DATE
[cordova]  :CordovaLib:processDebugManifest UP-TO-DATE
[cordova]  :CordovaLib:processDebugResources
[cordova]  :CordovaLib:generateDebugSources
[cordova]  :CordovaLib:javaPreCompileDebug UP-TO-DATE
[cordova]  Note: Some input files use or override a deprecated API.
[cordova]  Note: Recompile with -Xlint:deprecation for details.
[cordova]  :CordovaLib:compileDebugJavaWithJavac
[cordova]  :CordovaLib:processDebugJavaRes NO-SOURCE
[cordova]  :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
[cordova]  :app:preBuild UP-TO-DATE
[cordova]  :app:preDebugBuild
[cordova]  :app:compileDebugAidl
[cordova]  :CordovaLib:packageDebugRenderscript NO-SOURCE
[cordova]  :app:compileDebugRenderscript
[cordova]  :app:checkDebugManifest
[cordova]  :app:generateDebugBuildConfig
[cordova]  :app:prepareLintJar
[cordova]  :app:generateDebugResValues
[cordova]  :app:generateDebugResources
[cordova]  :app:mergeDebugResources
[cordova]  :app:createDebugCompatibleScreenManifests
[cordova]  :app:processDebugManifest
[cordova]  :app:splitsDiscoveryTaskDebug
[cordova]  /Users/myUser/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/8672301b54694f15bf6f5102a5e69daa/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
[cordova]      
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
[cordova]      
[cordova]  /Users/myUser/.gradle/caches/transforms-1/files-1.1/instabug-core-8.1.1.aar/d3c0417a032f26dcef3ffe2eb6e1b52f/res/values/values.xml:132:5-52: AAPT: error: resource android:attr/fontVariationSettings not found.
[cordova]      
[cordova]  /Users/myUser/.gradle/caches/transforms-1/files-1.1/instabug-core-8.1.1.aar/d3c0417a032f26dcef3ffe2eb6e1b52f/res/values/values.xml:132:5-52: AAPT: error: resource android:attr/ttcIndex not found.
[cordova]      
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:580: error: resource android:attr/fontVariationSettings not found.
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:580: error: resource android:attr/ttcIndex not found.
[cordova]  error: failed linking references.
[cordova]  
[cordova]  Failed to execute aapt
[cordova]  com.android.ide.common.process.ProcessException: Failed to execute aapt
[cordova]  	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
[cordova]  	at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
[cordova]  	at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
[cordova]  	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
[cordova]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[cordova]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[cordova]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[cordova]  	at java.lang.reflect.Method.invoke(Method.java:498)
[cordova]  	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
[cordova]  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
[cordova]  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
[cordova]  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
[cordova]  	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
[cordova]  	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
[cordova]  	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[cordova]  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
[cordova]  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[cordova]  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[cordova]  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[cordova]  	at java.lang.Thread.run(Thread.java:745)
[cordova]  Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
[cordova]  	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
[cordova]  	... 48 more
[cordova]  Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
[cordova]  	at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[cordova]  	... 1 more
[cordova]  Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
[cordova]  	at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:463)
[cordova]  	at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
[cordova]  	at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
[cordova]  	at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)
[cordova]  :app:processDebugResources FAILED
[cordova]  
[cordova]  FAILURE: Build failed with an exception.
[cordova]  
[cordova]  * What went wrong:
[cordova]  Execution failed for task ':app:processDebugResources'.
[cordova]  > Failed to execute aapt
[cordova]  
[cordova]  * Try:
[cordova]  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[cordova]  
[cordova]  * Get more help at https://help.gradle.org
[cordova]  
[cordova]  BUILD FAILED in 14s
[cordova]  25 actionable tasks: 15 executed, 10 up-to-date
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/gradlew: Command failed with exit code 1 Error output:
[cordova]  Note: Some input files use or override a deprecated API.
[cordova]  Note: Recompile with -Xlint:deprecation for details.
[cordova]  /Users/myUser/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/8672301b54694f15bf6f5102a5e69daa/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
[cordova]      
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
[cordova]      
[cordova]  /Users/myUser/.gradle/caches/transforms-1/files-1.1/instabug-core-8.1.1.aar/d3c0417a032f26dcef3ffe2eb6e1b52f/res/values/values.xml:132:5-52: AAPT: error: resource android:attr/fontVariationSettings not found.
[cordova]      
[cordova]  /Users/myUser/.gradle/caches/transforms-1/files-1.1/instabug-core-8.1.1.aar/d3c0417a032f26dcef3ffe2eb6e1b52f/res/values/values.xml:132:5-52: AAPT: error: resource android:attr/ttcIndex not found.
[cordova]      
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:580: error: resource android:attr/fontVariationSettings not found.
[cordova]  /Users/myUser/Documents/projects/myProject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:580: error: resource android:attr/ttcIndex not found.
[cordova]  error: failed linking references.
[cordova]  
[cordova]  Failed to execute aapt
[cordova]  com.android.ide.common.process.ProcessException: Failed to execute aapt
[cordova]  	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
[cordova]  	at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
[cordova]  	at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
[cordova]  	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
[cordova]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[cordova]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[cordova]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[cordova]  	at java.lang.reflect.Method.invoke(Method.java:498)
[cordova]  	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
[cordova]  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
[cordova]  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
[cordova]  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
[cordova]  	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
[cordova]  	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
[cordova]  	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
[cordova]  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
[cordova]  	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[cordova]  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
[cordova]  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
[cordova]  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
[cordova]  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[cordova]  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[cordova]  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[cordova]  	at java.lang.Thread.run(Thread.java:745)
[cordova]  Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
[cordova]  	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
[cordova]  	... 48 more
[cordova]  Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
[cordova]  	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
[cordova]  	at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[cordova]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[cordova]  	... 1 more
[cordova]  Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
[cordova]  	at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:463)
[cordova]  	at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
[cordova]  	at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
[cordova]  	at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)
[cordova]  
[cordova]  FAILURE: Build failed with an exception.
[cordova]  
[cordova]  * What went wrong:
[cordova]  Execution failed for task ':app:processDebugResources'.
[cordova]  > Failed to execute aapt
[cordova]  
[cordova]  * Try:
[cordova]  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[cordova]  
[cordova]  * Get more help at https://help.gradle.org
[cordova]  
[cordova]  BUILD FAILED in 14s
```
Ionic info
```
ionic info

Ionic:

   ionic (Ionic CLI)             : 4.11.0 (/Users/lucky/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.0
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   NodeJS : v10.11.0 (/Users/myUser/.nvm/versions/node/v10.11.0/bin/node)
   npm    : 6.8.0
   OS     : macOS High Sierra
   Xcode  : Xcode 10.1 Build version 10B61
```

Many thanks :)

**Comment by salmamali** [comment]
This is happening because Instabug targets sdk 28. You need to update it by opening the file `platforms/android/project.properties` and changing it as follows:

```
target=android-28
```

**Comment by luckylooke** [comment]
Great, now instabug works! Thanks!!! :)
